version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=test-topic:1:1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
  web-app:
    build: .
    profiles:
      - "not-supported-yet"
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=test-topic
      - KAFKA_GROUP_ID=my-group
      - KAFKA_OFFSET=latest
      - HTTP_PORT=8080
      - HTTP_READ_TIMEOUT=10
      - HTTP_WRITE_TIMEOUT=10
      - HTTP_IDLE_TIMEOUT=10
    ports:
      - '8080:8080'
    depends_on:
      - kafka