version: '3'

services:
  kafka-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
      - '3000:3000'
    environment:
      # Basic Kafka Configuration
      - KAFKA_BROKERS=${KAFKA_BROKERS:-localhost:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-test-topic}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-my-group}
      - KAFKA_OFFSET=${KAFKA_OFFSET:-latest}
      
      # HTTP Configuration
      - HTTP_PORT=5001
      - HTTP_READ_TIMEOUT=10
      - HTTP_WRITE_TIMEOUT=10
      - HTTP_IDLE_TIMEOUT=10
      
      # AWS MSK Configuration
      - AWS_REGION=${AWS_REGION:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      
      # Kafka Security Configuration
      - KAFKA_USERNAME=${KAFKA_USERNAME:-}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD:-}
      - USE_SASL=${USE_SASL:-false}
      - USE_SSL=${USE_SSL:-false}
      - SSL_CA_LOCATION=${SSL_CA_LOCATION:-}
      - SSL_CERT_LOCATION=${SSL_CERT_LOCATION:-}
      - SSL_KEY_LOCATION=${SSL_KEY_LOCATION:-}
      - SASL_MECHANISM=${SASL_MECHANISM:-SCRAM-SHA-512}
      
      # Frontend Configuration
      - VITE_API_URL=http://localhost:5001
    volumes:
      - ./live-view-webapp:/app/frontend
      - ./static:/app/static
      # Mount SSL certificates if needed
      - ${SSL_CERTS_PATH:-./certs}:/app/certs